name: my_new_movie_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.0
  http: ^1.2.0
  wakelock_plus: ^1.3.2
  provider: ^6.0.5
  video_player: ^2.5.1
  chewie: ^1.7.0
  unity_ads_plugin: ^0.3.0
  connectivity_plus: ^5.0.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_icon.png
    - assets/images/custom_banner.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
